services:
  calliope:
    container_name: calliope_core
    image: calliope:1.0.0
    restart: "unless-stopped"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - MONGO_URI=mongodb://mongodb:27017
      - REDIS_URI=redis://redis:6379
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    command: ["poetry", "run", "env", "PYTHONPATH=.", "python", "-m", "calliope", "-v", "True"]

  mongodb:
    image: mongo:8.0.0-rc6
    container_name: "mongodb_calliope"
    restart: "unless-stopped"
    ports:
      - "27018:27017"
    volumes:
      - mongodb_calliope:/data/db

  redis:
    image: "redis:7.2.5-alpine"
    restart: "unless-stopped"
    container_name: "caliope-redis"
    ports:
      - "6380:6379"
    volumes:
      - caliope_redis_data:/data
      # - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server"] #, "/usr/local/etc/redis/redis.conf"]

volumes:
  mongodb_calliope:
  caliope_redis_data:
