version: "3"

services:
  calliope:
    container_name: calliope_core
    image: calliope
    restart: "unless-stopped"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - WICH_GPU=1
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
  mongodb:
    image: mongo:8.0.0-rc6
    container_name: "mongodb_calliope"
    restart: "unless-stopped"
    ports:
      - "27018:27017"
    volumes:
      - mongodb_calliope:/data/db

volumes:
  mongodb_calliope:
