services:
  calliope:
    container_name: calliope_core
    image: calliope:1.0.0
    restart: "unless-stopped"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - MONGO_URI=mongodb://mongodb:27017
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    command: ["poetry", "run", "env", "PYTHONPATH=.", "python", "-m", "calliope", "-v", "True"]

  mongodb:
    image: mongo:8.0.0-rc6
    container_name: "mongodb_calliope"
    restart: "unless-stopped"
    ports:
      - "27018:27017"
    volumes:
      - mongodb_calliope:/data/db

volumes:
  mongodb_calliope:
