[tool.poetry]
name = "calliope"
version = "0.1.0"
description = ""
authors = ["Matteo Donato <matteo.donato@joule.video>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torch = "2.0.0"
torchvision = "0.15.1"
torchaudio = "2.0.1"
python-telegram-bot = "^20.6"
transformers = "^4.35.1"
librosa = "^0.10.1"
rich = "^13.6.0"
moviepy = "^1.0.3"
loguru = "^0.7.2"
pandas = "^2.1.3"
pydantic = "^2.6.1"


[tool.poetry.group.dev.dependencies]
memory-profiler = "^0.61.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
